In [1]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\kerim\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.08.22 |       haa95532_0         123 KB
    certifi-2023.7.22          |  py310haa95532_0         154 KB
    openssl-1.1.1w             |       h2bbff1b_0         5.5 MB
    ------------------------------------------------------------
                                           Total:         5.8 MB

The following packages will be UPDATED:

  ca-certificates                     2023.01.10-haa95532_0 --> 2023.08.22-haa95532_0 
  certifi                         2022.12.7-py310haa95532_0 --> 2023.7.22-py310haa95532_0 
  openssl                                 1.1.1t-h2bbff1b_0 --> 1.1.1w-h2bbff1b_0 




ca-certificates-2023 | 123 KB    |            |   0% 

openssl-1.1.1w     



==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.10.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.10.0




In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
#numpy array

In [7]:
my_list = [10, 20, 30, 40]

In [8]:
type(my_list)

list

In [9]:
np.array(my_list)

array([10, 20, 30, 40])

In [10]:
my_numpy_array = np.array(my_list)

In [11]:
type(my_numpy_array)

numpy.ndarray

In [12]:
my_numpy_array[0]

10

In [13]:
my_numpy_array.min()

10

In [14]:
my_numpy_array.max()

40

In [15]:
my_numpy_array.mean()

25.0

In [16]:
matrix_list = [[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [18]:
numpy_matrix_list = np.array(matrix_list)

In [19]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [21]:
numpy_matrix_list.shape

(4, 3)

In [22]:
#range

In [23]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
#linspace

In [31]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [32]:
#random

In [34]:
np.random.randint(1,10,3)

array([4, 9, 9])

In [36]:
np.random.randint(1,100,10)

array([48, 21, 39, 63, 63, 55, 95, 63, 62, 89])

In [37]:
#numpy arrays methods

In [38]:
my_numpy_list = np.arange(0,20)

In [39]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
my_numpy_list[4:9]

array([4, 5, 6, 7, 8])

In [41]:
my_list = list(range(0,20))

In [42]:
#my_list [4,9] = -10 

In [43]:
my_numpy_list [4:9] = -10

In [44]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [45]:
other_list = np.arange(0,15)

In [46]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
other_list[4:10]

array([4, 5, 6, 7, 8, 9])

In [48]:
slicing_list = other_list[4:10]

In [49]:
slicing_list[0]

4

In [50]:
slicing_list[:] = 100 #bütün elemanlar

In [51]:
slicing_list

array([100, 100, 100, 100, 100, 100])

In [52]:
other_list

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [53]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [54]:
numpy_list_3 = np.arange(0,20)

In [55]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
numpy_list_3_copy = numpy_list_3.copy()

numpy_list_3_copy 

In [58]:
numpy_list_3_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
slicing_3 = numpy_list_3_copy

In [60]:
slicing_3[:] = -100

In [61]:
slicing_3

array([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
       -100, -100, -100, -100, -100, -100, -100, -100, -100])

In [62]:
numpy_list_3_copy

array([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
       -100, -100, -100, -100, -100, -100, -100, -100, -100])

In [63]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
#numpy operations with numpy arrays

In [65]:
new_array = np.random.randint(1,150,25)

In [66]:
new_array

array([ 84, 113,  94,  45, 123,  37,  55, 147,  79,  32,  71, 120,  10,
       137,  81,  18, 105,  67, 114,  48,  79,  80,  69,  47,  96])

In [67]:
new_array > 50

array([ True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True,  True,  True, False,  True])

In [68]:
result_array = new_array > 50

In [69]:
result_array

array([ True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True,  True,  True, False,  True])

In [70]:
new_array

array([ 84, 113,  94,  45, 123,  37,  55, 147,  79,  32,  71, 120,  10,
       137,  81,  18, 105,  67, 114,  48,  79,  80,  69,  47,  96])

In [72]:
new_array[result_array]

array([ 84, 113,  94, 123,  55, 147,  79,  71, 120, 137,  81, 105,  67,
       114,  79,  80,  69,  96])

In [73]:
last_array = np.arange(0,30)

In [75]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [76]:
last_array + last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [77]:
last_array * last_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [78]:
np.max(last_array)

29

In [79]:
last_array.max()

29

In [80]:
np.mean(last_array)

14.5

In [81]:
np.sqrt(last_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])